version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: vapor
      POSTGRES_DB: vapor
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    image: 'redis:7-alpine'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
